<div class="row">
    <div class="col-md-6">
        <div class="card bg-light mb-3">
            <div class="card-header">
                <?php echo _a('Comment stats'); ?>
            </div>
            <table class="table table-responsive">
                <tr>
                    <th><?php echo _a('Title'); ?>
                    <th><?php echo _a('Amounts'); ?>
                </tr>
                <?php foreach ($counts as $name => $data) { ?>
                    <tr>
                        <td>
                            <?php echo _escape($data['title']); ?>
                        </td>
                        <td>
                            <a href="<?php echo $data['url']; ?>"
                               title="<?php echo _escape($data['title']); ?>" target="_blank">
                                <?php echo $data['count']; ?>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <div class="card bg-light mb-3">
            <div class="card-header"><?php echo _a('Top posters'); ?></div>
            <table class="table table-striped">
                <tr>
                    <th></th>
                    <th><?php echo _a('Submitters'); ?></th>
                    <th><?php echo _a('Comments'); ?></th>
                </tr>
                <?php
                $index = 0;
                foreach ($users as $uid => $data) {
                    ?>
                    <tr>
                        <td><?php echo _escape(++$index); ?></td>
                        <td><?php echo _escape($data['name']); ?></td>
                        <td>
                            <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['name']); ?>" target="_blank">
                                <?php echo $data['count']; ?>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <div class="card bg-light mb-3">
            <div class="card-header"><?php echo _a('Active comment posts by module'); ?></div>
            <table class="table table-striped">
                <tr>
                    <th><?php echo _a('Title'); ?></th>
                    <th><?php echo _a('Amounts'); ?></th>
                </tr>
                <?php foreach ($modules as $name => $data) { ?>
                    <tr>
                        <td><?php echo _escape($data['title']); ?></td>
                        <td><a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>" target="_blank">
                                <?php echo $data['count']; ?>
                            </a></td>
                    </tr>
                    <?php foreach ($data['types'] as $type => $cData) { ?>
                        <tr>
                            <td>&nbsp;&nbsp;<?php echo _escape($cData['title']); ?></td>
                            <td><a href="<?php echo $cData['url']; ?>" title="<?php echo _escape($cData['title']); ?>" target="_blank">
                                    <?php echo $cData['count']; ?></a>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
            </table>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card bg-light mb-3">
            <div class="card-header"><?php echo _a('Links'); ?></div>
            <div class="card-text">
                <ul>
                    <?php foreach ($links as $name => $data) { ?>
                        <li>
                            <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>" target="_blank">
                                <?php echo _escape($data['title']); ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div class="card bg-light mb-3">
            <div class="card-header"><?php echo _a('Most commented'); ?></div>
            <table class="table table-striped">
                <tr>
                    <th></th>
                    <th><?php echo _a('Article title'); ?></th>
                    <th><?php echo _a('Comments'); ?></th>
                </tr>
                <?php
                $index = 0;
                foreach ($targets as $name => $data) {
                    ?>
                    <tr>
                        <td><?php echo _escape(++$index); ?></td>
                        <td><?php echo _escape($data['title']); ?></td>
                        <td>
                            <a href="<?php echo $data['url']; ?>" title="<?php echo _escape($data['title']); ?>" target="_blank">
                                <?php echo $data['count']; ?>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>
