<?php $this->css($this->assetModule('css/block.css', 'comment')); ?>
<div class="pi-comment pi-comment-block-post">
    <?php if ($block['posts']) { ?>
    <div class="pi-comment-list" itemscope itemtype="https://schema.org/UserComments">
    <?php foreach ($block['posts'] as $post) { ?>
        <div class="media">
            <a class="pull-left" href="<?php echo $post['user']['url']; ?>" target="_blank">
                <?php echo $post['user']['avatar']; ?>
            </a>
            <div class="media-body">
                <div class="pi-comment-box">
                    <span itemprop="creator" itemscope itemtype="https://schema.org/Person">
                        <span class="pi-comment-user" itemprop="name">
                            <a href="<?php echo $post['user']['url']; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                                <?php echo $post['user']['name']; ?>
                            </a>
                        </span>
                    </span>
                    <span class="pull-right muted pi-comment-time"><?php echo _date($post['time']); ?></span>
                    <meta itemprop="commentTime" content="<?php echo date("Y-m-d H:i:s", $post['time']); ?>" />
                </div>
                <div class="pi-comment-desc">
                    <span class="muted pull-left">
                        <?php echo _b('On '); ?>
                        <a class="highlight" href="<?php echo $post['target']['url']; ?>" title="<?php echo $post['target']['title']; ?>">
                            <?php echo $post['target']['title']; ?>
                        </a>
                    </span>
                </div>
                <div class="pi-comment-content" itemprop="commentText">
                    <?php echo mb_substr(strip_tags($post['content']), 0, 300, 'utf-8') . " ..."; ?>
                </div>
            </div>
        </div>
    <?php } ?>
    </div>
    <?php } else { ?>
    <div class="pi-comment-none"><?php echo _b('No comments available yet.'); ?></div>
    <?php  } ?>
</div>