<?php
if (isset($root['active']) && empty($root['active'])) {
    echo '<div class="well well-sm">' . __('Comment is disabled.') . '</div>';
    return;
}

$colClass = '';
$userId = Pi::user()->getId();
$guestApprove = Pi::service('config')->get('guest_approve', 'comment');
$url = Pi::service('url')->assemble('default', array(
    'module'        => 'system',
    'controller'    => 'index',
    'action'        => 'user',
));

if (!empty($root['id'])) {
    $formData = array(
        'root' => $root['id']
    );
} else {
    $formData = array(
        'module'    => $root['module'],
        'type'      => $root['type'],
        'item'      => $root['item'],
    );
}
$formData['redirect'] = rawurlencode($uri);

$options = array();
$options['review'] = $review;
$form = Pi::service('comment')->getForm($formData, $options);
?>

<div class="comment-item" id="js-comment-form">
    <?php echo $this->form()->openTag($form); ?>
    <div class="form-group">
        <textarea placeholder="<?php _e('Type your content'); ?>" class="form-control js-comment-txt" rows="3"></textarea>
    </div>
    <div class="hide clearfix comment-form form-group">
        <div id="special-review">
        <?php if ($review)  { ?>
            <div id="ratings">
                <?php foreach ($form->ratings as $key => $rating) { ?> 
                    <div class="col-md-4 inline">
                        <?php echo $this->formElement($form->get('star-' . $key)); ?>    
                        <?php echo $this->formElement($form->get('rating-' . $key)); ?>
                    </div>
                <?php } ?>
            </div>
            <div class="clearfix"></div>
            
            <div class="col-md-8 inline">
                <label><?php _e('Experience time') ?></label>
                    <?php echo $this->formElement($form->get('time_experience')); ?>
            </div>
        <?php } ?>
    </div>
        <?php echo $this->formElement($form->get('reply')); ?>
        <?php echo $this->formElement($form->get('id')); ?>
        
        <?php echo $this->formElement($form->get('content')); ?>
        <?php if ($review)  { ?>
            <br/>
            <?php echo $this->formMedia($form->get('main_image')); ?>
            <?php echo $this->formMedia($form->get('additional_images')); ?>
        <?php } ?>
    </div>
    <?php if ($guestApprove === 1 && $userId === 0) { ?>
        <div class="row hide clearfix comment-form-guest col-md-8">
            <div class="col-md-6">
                <div class="form-group">
                    <label><?php _e('Name'); ?></label>
                    <?php echo $this->formElement($form->get('identity')); ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label><?php _e('Email'); ?></label>
                    <?php echo $this->formElement($form->get('email')); ?>
                </div>
            </div>
        </div>
        <?php $colClass = 'col-md-4'; ?>
    <?php } ?>
    <div class="hide clearfix comment-form <?php echo $colClass; ?> text-right">
        <a href="#" class="hide cancel btn btn-primary"><?php _e('Cancel') ?></a>
        <?php echo $this->formElement($form->get('submit')); ?>
    </div>
    <div class="hide clearfix comment-form">
        <?php
        $elements = $form->elementList();
        foreach ($elements['hidden'] as $element) {
            echo $this->formElement($element);
        }
        ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <?php if (!$userId && !$guestApprove) { ?>
        <div class="hide well well-sm comment-login">
            <?php $modalEnabled = Pi::user()->config('enable_modal'); ?>
            <?php echo sprintf(__('Please <a href="%s" data-target="#loginRegisterModal" data-redirect-anchor="#pi-comment-lead-anchor" data-action="login" data-toggle="%s">login</a> to leave comments.'), $modalEnabled ? '#' : Pi::service('authentication')->getUrl('login', $uri), $modalEnabled ? 'modal' : ''); ?>
        </div>
    <?php } ?>
</div>
<script>
    (function ($) {
        var comment = {
            el: $('#js-comment-form'),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                this.textarea = this.$('.js-comment-txt');
                this.events();
            },
            events: function () {
                var self = this;
                var guest = <?php echo $guestApprove; ?>;
                this.textarea.focus(function () {
                    $.getJSON('<?php echo $url; ?>?' + new Date().getTime()).done(function (data) {
                        self.textarea.hide();
                        if (data.uid) {
                            self.$('.comment-form').removeClass('hide');
                            self.$('[name=content]').focus();
                        } else if (guest == 1) {
                            self.$('.comment-form').removeClass('hide');
                            self.$('.comment-form-guest').removeClass('hide');
                            self.$('[name=content]').focus();
                        } else {
                            self.$('.comment-login').removeClass('hide');
                        }
                    });
                });
            }
        };
        comment.init();
    })(jQuery)
</script>
<div class="pi-status active js-comment-status" data-id="">
    <div class="pi-status-director"></div>
</div>
<script>
    $('.js-comment-status').click(function() {
        location.href = '<?php $this->url(); ?>' + $(this).data('id');
    });
</script>