<?php
$this->jQuery();
$this->backbone();
$this->css($this->assetModule('css/front.css', 'comment'));
$this->headMeta('noindex', 'robots');

// Target data:
// Title, time, user
// uid, name, avatar, profile_url
$target = $comment['target'];

// Comment post
// content, time, user
$post = $comment['post'];
?>
<div class="pi-comment">
    <h1 class="pi-comment-header"><?php _e('Comment detail'); ?></h1>
    <div class="media">
        <?php if ($post['uid'] > 0) { ?>
            <a class="pull-left" href="<?php echo $post['user']['url']; ?>">
                <?php echo Pi::avatar()->get($post['uid'], 'medium'); ?>
            </a>
        <?php } else { ?>
            <p class="pull-left">
                <?php echo Pi::avatar()->get($post['uid'], 'medium'); ?>
            </p>
        <?php } ?>
        <div class="media-body">
            <?php if ($post) { ?>
                <div class="pi-comment-single">
                    <div class="clearfix ">
                        <ul class="list-inline">
                            <li class="list-inline-item pi-comment-user">
                                <?php if ($post['uid'] > 0) { ?>
                                    <a href="<?php echo $post['user']['url']; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                                        <?php echo $post['user']['name']; ?>
                                    </a>
                                <?php } else { ?>
                                    <?php echo $post['identity']; ?>
                                <?php } ?>
                            </li>
                            <?php if ($post['reply']) { ?>
                                <li class="list-inline-item" style="font-size: 14px"><?php _e('In reply to:'); ?></li>
                                <li class="list-inline-item" style="font-size: 14px"><a class="highlight" href="<?php echo Pi::service('comment')->getUrl('post', array('post' => $post['reply'])); ?>" target="_blank" title="<?php _e('Click to open'); ?>">
                                        <?php echo sprintf(__('Comment #%d'), $post['reply']); ?>
                                    </a>
                                </li>
                            <?php } ?>
                            <li class="list-inline-item pull-right muted pi-comment-time"><?php echo _date($post['time']); ?></li>
                        </ul>
                    </div>
                    <div class="pi-comment-desc">
                        <ul class="list-inline">
                            <li class="list-inline-item muted pull-left"><?php _e('Commented on '); ?></li>
                            <li class="list-inline-item">
                                <a href="<?php echo $target['url']; ?>" title="<?php echo _escape($target['title']); ?>">
                                    <?php echo _escape($target['title']); ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="pi-comment-content">
                        <?php echo $post['content']; ?>
                    </div>
                    <?php if ($post['uid'] > 0) { ?>
                        <div class="pi-comment-operation">
                            <ul class="list-inline">
                                <?php foreach ($post['operations'] as $operation => $optData) { ?>
                                    <li class="list-inline-item operation muted">
                                        <a href="<?php echo $optData['url']; ?>"<?php echo 'delete' == $operation ? sprintf(' onclick="return confirm(\'%s\')"', __('Are you sure to delete this comment?')) : ''; ?>>
                                            <?php echo _escape($optData['title']); ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <div class="pi-comment-none"><?php _e('No content.'); ?></div>
            <?php } ?>
        </div>
    </div>
</div>