<?php 
    $this->jQuery(array(
        'extension/jquery.magnific-popup.min.js',
        'extension/magnific-popup.css',
    ));
    if (!empty($script)) {
        $this->footScript()->appendScript($script);
    }
    $this->css($this->assetModule('css/front.css', 'comment')); 
    
?>
<script>
    $(function() {
        initGallery = function()
        {
            $('.gallery').each(function() {
                $(this).magnificPopup({
                    delegate: 'a',
                    type: 'image',
                    gallery: {
                        enabled:true
                    }
                });
            });
        }
        var cancel = function() {
            // time experience
            if ($('form#review-post [name=time_experience]').length) {
                $('form#review-post [name=time_experience]').datepicker("setDate", null);
                $('form#review-post [name=time_experience]').attr("required", true);
            }
            //
            
            $('form#comment-post textarea[name=content]').html('');
            $('form#review-post textarea[name=content]').html(''); 
             
            $('form#comment-post [name=id]').val(null);
            $('form#review-post [name=id]').val(null);
            
            $('form#comment-post [name=reply]').val(null);
            $('form#review-post [name=reply]').val(null);
                        
            // ratings
            $('#ratings input[type=hidden]').val(null)
            $('#ratings .active').removeClass('active')
            //
            
            // images
            $('form#review-post [name=main_image]').val(null);
                $('form#review-post [name=additional_images]').val(null);
                $( ".media-form-list" ).each(function(){
                    refreshFormList($(this));
                });
            //
            
            $('.cancel').addClass('hide');
            $('.special-review').show();
        }
        
        var initCancel = function() {
            $('.btn.cancel').click(
                function(e) {
                    e.preventDefault();
                    cancel();
                    $('#modalForm').modal('hide');
                    return false;
                }
            );
        }
        
        var reply = function (elem, review) {
            var form = review ? $('form#review-post') : $('form#comment-post');
            form.find('[name=reply]').val($(elem).data('reply'));
            form.find('[name=time_experience]').attr("required", false);
             
            form.find('.cancel').removeClass('hide');
            $('.special-review').hide();
        };
        
        var initReply = function() {
            $('.reply').click(
                function(e) {
                    e.preventDefault();
                    cancel();
                    var review = $(this).parent().hasClass('is-review') == true;
                    reply(this, review);
                    showForm(review);
                    
                    return false;
                }
                
            );    
        };
        
        var edit = function(elem) {
            var review = $(elem).parent().hasClass('is-review');
            var form = review ? $('form#review-post') : $('form#comment-post');
             
            form.find('.cancel').removeClass('hide');
            var html = $(elem).parent().parent().find(".commentText").html();
            form.find('[name=id]').val($(elem).data('id'));
            var isReply = $(elem).parent().hasClass('is-reply');
            if (isReply) {
                reply(elem);
                var replyId =  $(elem).parent().parent().parent().data('reply')
                form.find('[name=reply]').val(replyId);
                form.find('textarea[name=content]').html(html);
                form.find('[name=time_experience]').attr("required", false);

            } else {
                
                form.find('textarea[name=content]').html(html);
                if (form.find('[name=time_experience]').length) {
                    var timeExperience = $(elem).parent().parent().find('.time-experience').data('time');
                    form.find('[name=time_experience]').datepicker("setDate", timeExperience);
                }
                var ratings = $(elem).parent().parent().find('.ratings div');
                ratings.each(
                    function (index)
                    {
                        var id = $(this).attr('for');
                        var rating = $(this).data('value');
                        form.find('[name=' + id + ']').val(rating);
                        form.find('[for=' + id + '] a[data-value=' + rating + ']').addClass('active');
                    }
                    
                );
                var images = $(elem).parent().parent().find('.images');
                form.find('[name=main_image]').val(images.data('main_image'));
                form.find('[name=additional_images]').val(images.data('additional_images'));
                $( ".media-form-list" ).each(function(){
                    refreshFormList($(this));
                });
            }
            
        };
        
        var initEdit = function() {
            $('.edit').click(
                function (e) {
                    e.preventDefault();
                    cancel(e);
                    edit(this);
                    
                    var review = $(this).parent().hasClass('is-review') == true;
                    showForm(review);
                    
                    return false;
                }
            );    
        };
        
        initReply();
        initEdit();
        initCancel();
        
        
        $('.paginator').click(
            function () {
                  var page = $(this).data('page');
                  var type = $(this).data('type');
                  $(this).parent().parent().find('li').removeClass('active');
                  $(this).parent().addClass('active');
                   
                  var uri = "<?php echo Pi::service('url')->assemble('comment', array(
                    'module'        => 'comment',
                    'controller'    => 'index',
                    'action'        => 'page',
                    
                 ));?>";
                  $.getJSON(uri, {
                    uri: $(location).attr('href'),
                    page: page,
                    type: type
                })
                .done(function (data) {
                    if (data.content) {
                        var el = $('#paginate-' + type + 's');
                       
                        el.attr('class','show').html(data.content);
                        initReply();
                        initEdit();
                        initGallery();
                    }
                });
                
                return false;
            }
        );
        
        $('.subscription').change(
            function () {
                var subscription = $('.subscription').prop('checked') == true ? 1 : 0;
                var uri = "<?php echo Pi::service('url')->assemble('comment', array(
                    'module'        => 'comment',
                    'controller'    => 'index',
                    'action'        => 'subscription',
                    
                ));?>";
                 
                $.getJSON(uri, {
                    uri: $(location).attr('href'),
                    subscription: subscription
                })
                .done(function (data) {
                    
                });
                
                return false;
            }
        );
        var showForm = function(review)
        {

            if (review) {
                $('#modalForm').modal();
            } else {
                $('textarea.js-comment-txt')[0].focus();
            }
        };
            
        <?php if ($review) { ?>
            $('#js-review-form').removeClass('hide');
            
            $('.show-modal').click(
                function(e)
                {
                    // Permet au bouton Dejà Fait d'aller se positionner sur l'ancre
                    if ($(this).hasClass('noprevent') == 0) {
                        e.preventDefault();
                    }
                    cancel();
                    showForm(true);    
                }
            );
        <?php } ?>
            
    });
</script>
<?php

$templateRating =<<<'EOT'
    <div class="rating inline-block">
        <span class="fa fa-star %s"></span>
        <span class="fa fa-star %s"></span>
        <span class="fa fa-star %s"></span>
        <span class="fa fa-star %s"></span>
        <span class="fa fa-star %s"></span>
    </div>
EOT;

?>
<div class="panel panel-default nodeco" id="comments">
    <?php if ($review) { ?>
        <div class="row panel-heading resume-ratings">
            <div>
                <?php  
                    $star = sprintf($templateRating, 
                        $globalRatings[0]['rating'] == 5 ? 'active' : '',
                        $globalRatings[0]['rating'] == 4 ? 'active' : '',
                        $globalRatings[0]['rating'] == 3 ? 'active' : '',
                        $globalRatings[0]['rating'] == 2 ? 'active' : '',
                        $globalRatings[0]['rating'] == 1 ? 'active' : ''
                    );  
                ?>
                
                <h2 class="panel-title inline-block">
                    <?php _e('All comments '); ?>
                    <strong>(<?php echo _number($count) ?: _number(0); ?>)</strong>
                </h2>
                &nbsp;<?php echo $star; ?> <?php echo $globalRatings[0]['number'] >= 1 ? $globalRatings[0]['number'] : '' ?>
                <?php if (Pi::user()->getId() > 0 && method_exists(Pi::api('comment', Pi::service('module')->current()), 'canonize')) { ?>
                    <input class="subscription" type="checkbox" <?php echo $subscribe ? 'CHECKED=CHECKED' : '' ?> /> <span class="text-muted"><?php _e('Subscribe to the thread') ?></span>
                <?php } ?>
            </div>
            <div class="col-md-4 no-padding">Résumé</div>
            <div class="col-md-8">
                <?php foreach ($globalRatings as $key => $rating)  { ?>
                    <?php if ($key ==0) {
                        continue; 
                    } ?>
                    <div class="col-md-6">
                        <?php  
                            $star = sprintf($templateRating, 
                                $rating['rating'] == 5 ? 'active' : '',
                                $rating['rating'] == 4 ? 'active' : '',
                                $rating['rating'] == 3 ? 'active' : '',
                                $rating['rating'] == 2 ? 'active' : '',
                                $rating['rating'] == 1 ? 'active' : ''
                            );  
                        ?>
                       <span class="inline-block" style="width:70px"><?php echo $key == 0 ? __($rating['type']) : $rating['type'] ?></span>  
                       <?php echo $star ?>
                    </div>    
                <?php } ?>  
            </div>
        </div>
    <?php } else { ?>
        <div class="row panel-heading">
            <h2 class="panel-title inline-block">
                <?php _e('All comments '); ?>
                <strong>(<?php echo _number($count) ?: _number(0); ?>)</strong>
            </h2>
            &nbsp;<?php echo $star; ?> <?php echo $globalRatings[0]['number'] ?>
            <?php if (Pi::user()->getId() > 0 && method_exists(Pi::api('comment', Pi::service('module')->current()), 'canonize')) { ?>
                <input class="subscription" type="checkbox" <?php echo $subscribe ? 'CHECKED=CHECKED' : '' ?> /> <span class="text-muted"><?php _e('Subscribe to the thread') ?></span>
            <?php } ?>
        </div>
    <?php } ?> 
    <?php if ($review) { ?>
        <div id="write-review">
            <div class="write-review clearfix text-center">
                <a href="#" class="show-modal"><?php _e("Write a review") ?></a>
            </div>
        </div>
    <?php } ?>

    <div class="panel-body" itemscope itemtype="https://schema.org/UserComments">
        
        <?php include realpath(__FILE__) . './../_post-form.phtml' ?>
       
        <?php if (count($posts)) { ?>
            <div id="<?php echo $review ? 'paginate-reviews' : 'paginate-comments' ?>">
                <?php include realpath(__FILE__) . './../partial/paginate-comments.phtml' ?>
            </div>    
            <div class="text-center">
                <ul class="pagination">
                    <?php 
                    $pageNumber = $count % 5 == 0 ? $count / 5  : ((int) ($count / 5))  +1;
                    if ($pageNumber > 1) {
                        for ($i = 1; $i <= $pageNumber; ++$i) { ?>
                            <li class="<?php echo $i == 1 ? 'active' : '' ?>">
                                <a class="paginator" href="#" data-page="<?php echo $i ?>" data-type="<?php echo $review ? 'review' : 'comment' ?>">
                                    <?php echo $i ?>
                                </a>
                            </li>
                            
                     <?php
                        }  
                    } 
                    ?> 
                 </ul>
             </div>
        <?php } else { ?>
            <div class="text-center comment-none">
                <strong class="text-muted"><?php _e('No one has commented yet.'); ?></strong>
            </div>
        <?php } ?>
    </div>
</div>