<?php
$this->css($this->assetModule('css/front.css', 'comment'));
$this->headMeta('noindex', 'robots');

// Target data:
// title, time, user
// user: uid, name, avatar, url
$target = $comment['target'];

// Comment post
// content, time, user
$post = $comment['post'];

$uid = Pi::user()->getId();
if ($uid) {
    $url = Pi::service('user')->getUrl('profile', $uid);
} else {
    $url = Pi::url('www');
}
?>
<div class="pi-comment">
    <h1 class="pi-comment-header">
        <?php _e('Comment edit'); ?>
    </h1>
    <?php if (!empty($comment['message'])) { ?>
        <div class="alert alert-danger"><?php echo _escape($comment['message']); ?></div>
    <?php } ?>
    <div class="media">
        <a class="pull-left" href="<?php echo $url; ?>">
           <?php echo $post['user']['avatar']; ?>
        </a>
        <div class="media-body">
            <?php if ($post) { ?>
                <div class="clearfix">
                    <ul class="list-inline">
                        <li class="list-inline-item pi-comment-user">
                            <a href="<?php echo $url; ?>" target="_blank" title="<?php echo $post['user']['name']; ?>" class="highlight">
                                <?php echo $post['user']['name']; ?>
                            </a>
                        </li>
                        <li class="list-inline-item pull-right muted pi-comment-time"><?php echo _date($post['time']); ?></li>
                    </ul>
                </div>
                <div class="pi-comment-desc">
                    <span class="muted pull-left"><?php _e('Commented on '); ?>&nbsp;</span>
                    <a class="highlight" href="<?php echo Pi::url(Pi::api('api', 'comment')->getUrl('post', array('post' => $post['id']))) ?>" title="<?php echo _escape($target['title']); ?>">
                        <?php echo $target['title']; ?>
                    </a>
                </div>
                <?php echo $this->form()->openTag($form); ?>
                <div class="special-review">
            <?php if ($review && $post['reply'] == 0)  { ?>
                <input type="submit" id="rating_fakeinput" value="" onclick="return false"/>
                <div id="ratings" class="form-group">
                    <?php foreach ($form->ratings as $key => $rating) { ?> 
                        <div class="col-md-6 inline">
                            <?php echo $this->formElement($form->get('star-' . $key)); ?>    
                            <?php echo $this->formElement($form->get('rating-' . $key)); ?>
                        </div>
                    <?php } ?>
                    <div class="clearfix"></div>
                </div>
                
                <div class="col-md-12 inline form-group">
                    <div class="col-md-3 no-padding">
                        <label><i class="text-danger" style="margin-right: 5px;" title="Requis">*</i><?php _e('Experience time') ?></label>
                    </div>
                    <div class="col-md-9">
                        <?php echo $this->formElement($form->get('time_experience')); ?>
                    </div>
                </div>
            <?php } ?>
        </div>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('content')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>
                <?php
                $elements = $form->elementList();
                foreach ($elements['hidden'] as $element) {
                    echo $this->formElement($element);
                }
                echo $this->form()->closeTag();
            } else {
                ?>
                <div class="pi-comment-none"><?php _e('No content.'); ?></div>
            <?php } ?>
        </div>
    </div>
</div>


<script>
    (function ($) {
        var maxDate = new Date();
        $('form [name=time_experience]').datepicker('setEndDate', maxDate);
        $('.rating a').click(
            function () {
                  document.getElementById("rating_fakeinput").setCustomValidity("");
                  var id = $(this).parent().attr('data-for');
                  $('[name=' + id + ']').val($(this).data('value'));
                  $(this).parent().find('a').removeClass('active');
                  $(this).addClass('active');
                  return false;  
            }
        );
                        
<?php foreach ($ratings as $rating) { ?>
        $('[data-for=rating-<?php echo $rating['rating_type'] ?>] > a[data-value=<?php echo $rating['rating'] ?>]').addClass('active');   
<?php } ?>

    })(jQuery)
</script>
