<div class="panel panel-default" id="comments">
    <div class="panel-heading">
        <h2 class="panel-title">
            <?php _e('All comments '); ?>
            <strong>(<?php echo _number($count) ?: _number(0); ?>)</strong>
        </h2>
    </div>
    <div class="panel-body" itemscope itemtype="http://schema.org/UserComments">
        <?php include $this->template('./_post-form.phtml'); ?>
        <?php if (count($posts)) { ?>
            <?php
            $templateUser =<<<'EOT'
    <div class="media-heading" itemprop="creator" itemscope itemtype="http://schema.org/Person">
        <ul class="list-inline">
            <li><a href="%s" target="_blank" itemprop="name">%s</a></li>
            <li class="muted small">%s</li>
            <li class="muted small"><a href="%s" target="_blank"><i class="fa fa-external-link"></i></a></li>
        </ul>
    </div>
    <div class="clearfix" itemprop="commentText">%s</div>
    <meta itemprop="commentTime" content="%s" />
EOT;

            $templateGuest =<<<'EOT'
    <div class="media-heading" itemprop="creator" itemscope itemtype="http://schema.org/Person">
        <ul class="list-inline">
            <li>%s</li>
            <li class="muted small">%s</li>
            <li class="muted small"><a href="%s" target="_blank"><i class="fa fa-external-link"></i></a></li>
        </ul>
    </div>
    <div class="clearfix" itemprop="commentText">%s</div>
    <meta itemprop="commentTime" content="%s" />
EOT;
            ?>
            <?php foreach ($posts as $item) { ?>
                <?php $url = ($item['uid'] > 0) ? $item['user']['url'] : '#comments'; ?>
                <div class="pi-comment-single media comment-item clearfix" id="comment-<?php echo $item['id']; ?>">
                    <?php if ($item['uid'] > 0) { ?>
                        <a class="pull-left avatar-img-wrapper" href="<?php echo $item['user']['url']; ?>" target="_blank">
                            <?php echo $item['user']['avatar']; ?>
                        </a>
                    <?php } else { ?>
                        <p class="pull-left avatar-img-wrapper">
                            <?php echo $item['user']['avatar']; ?>
                        </p>
                    <?php } ?>
                    <div class="media-body">
                        <?php if ($item['uid'] > 0) {
                            echo sprintf(
                                $templateUser,
                                $url,
                                $item['user']['name'],
                                _date($item['time']),
                                $item['url'],
                                $item['content'],
                                date("Y-m-d H:i:s", $item['time'])
                            );
                        } else {
                            echo sprintf(
                                $templateGuest,
                                $item['identity'],
                                _date($item['time']),
                                $item['url'],
                                $item['content'],
                                date("Y-m-d H:i:s", $item['time'])
                            );
                        } ?>
                        <div class="comment-operation">
                            <?php if ($uid > 0 && $uid == $item['uid']) {
                                echo sprintf(
                                    '<a href="%s#comments" onclick="return confirm(\'%s\')">%s</a>',
                                    $this->url('comment', array('controller' => 'post', 'action' => 'delete', 'id' => $item['id'])),
                                    __('Are you sure to delete this comment?'),
                                    __('Delete')
                                );
                            } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <a href="<?php echo $url_list; ?>" class="btn btn-default btn-block view-all-comments-btn" style="margin-top: 10px;">
                <?php _e('View all comments'); ?>
            </a>
        <?php } else { ?>
            <div class="text-center comment-none">
                <strong class="text-muted"><?php _e('No one has commented yet.'); ?></strong>
            </div>
        <?php } ?>
    </div>
</div>