<div class="row">
    <div class="col-md-12">
        <div class="user-min-body pi-comment-list my pi-comment-lead">
            <p>&nbsp;</p>
            <?php if ($posts) { ?>
                
                <?php 
                    $badgeAdmin = Pi::service('config') -> get('badge_admin', 'comment');
                    include $this->templateModule('front/partial/paginate-comments-list-my', 'comment'); 
                ?>

                <?php
                if ($paginator) {
                    echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml',array('class' => 'pagination-left'));
                }
            } else { ?>
                <div class="card card-body bg-light mb-3">
                    <?php _e('No data available.'); ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>

